### ISSUE TITLE
Enlarge Headings

### ISSUE THREAD

**Issue by sophiabonsu** [hunter-college-ossd-fall-2019/jxuan101-weekly#1]
Hi I really enjoyed reading through your blog ! I think maybe capitalizing the sections will be more visually pleasing.

So perhaps :

# Learning and Using Git
I did a class activity using Git for the first time this week in my Open Source Software Development class. Unsurprisingly, Git is amazingly useful for managing and tracking repositories on Github. Git has simple and self-explanatory commands making it very easy to use even for beginners. Installation and setup also posed no difficulties at all. The class activity went smoothly. There were no problems completing the tasks given although it might have took a little bit of time for my team members to figure it out. I personally did not encounter any merge conflicts but I have learned how to resolve them.

# Article Review
Link to Article: A Beginner’s Very Bumpy Journey Through The World of Open Source

This article enbodies all my personal worries and problems with getting into open source development. Like the author, I have always felt incompetent whenever I try to make a contribution to an open source software. I felt like my contributions would be rejected and that trivial contributions such as fixing typos might be too simple to be considered a worthy contribution. Reading about the author's journey as an amateur open source contributer inspires me to be brave when aspiring to become an open source contributer because everything counts, no matter how small. Not everyone can contribute to big projects in the beginning so starting small seems to be the ideal beginning for a beginner open source contributer such as myself.

# Editing Blog Activity
I found some spelling mistakes on my classmate, Shakeel's blog post for week 1. I opened an issue for it and while it was trivial, it was an issue nonetheless. I forked the repository and cloned it to my local system. I fixed the spelling mistakes and tracked the file. I then committed the changes and pushed it onto my forked repository. Finally, I opened a pull request on Shakeel's repository to merge my changes. As of now, the pull request has not been merged but since it is of a trivial matter, the pull request would eventually be approved and merged. The workflow involved in this activity was much simpler than the workflow depicted in the slides. For one, no matter was done and extra steps to help reduce merge conflicts were ignored.

# Weekly Summary
Version Control and Git
Workflows and more Git
Git Activity
Blog Peer Review
Working on Projects

**Comment by jxuan101** [comment]
Hey sophiabonsu, I'm glad you liked my blog! I've incorporated your idea into my current blog posts and ones going forward. Thank you for your great suggestion.
